language: java
jdk: 
  - openjdk11

branches:
  only:
    - mater

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - nomj18@gamil.com

before_deploy:
  - zip -r helloshop-webservice *
  - mkdir -p deploy
  - mv helloshop-webservice.zip deploy/helloshop-webservice.zip


deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_key_id: $AWS_SECRET_KEY

    bucket: helloshop-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true