language: java
jdk: 
  - openjdk11

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - nomj18@gmail.com

#배포전 실행할 명령어들
before_deploy:
  - mkdir -p before-deploy
  - chmod +x scripts/*.sh #모든 sh파일에 실행 권한을 줌
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/helloshop-webservice.zip


deploy:
  - provider: s3 #아마존 s3 설정
    access_key_id: $AWS_ACCESS_KEY #AWS IAM 액세스 키
    secret_access_key: $AWS_SECRET_KEY #AWS IAM 비밀 키

    bucket: helloshop-build #s3 버킷이름
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true


  - provider: codedeploy #아마존 CodeDeploy 설정
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: helloshop-build
    key: helloshop-webservice.zip
    bundle_type: zip
    application: helloshop-webservice
    deployment_group: helloshop-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true

