language: java
jdk: 
  - openjdk11

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - nomj18@gmail.com

before_deploy:
  - chmod +x gradlew
  - zip -r helloshop-webservice *
  - mkdir -p deploy
  - mv helloshop-webservice.zip deploy/helloshop-webservice.zip


deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: helloshop-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true


  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: helloshop-build
    key: helloshop-webservice.zip
    bundle_type: zip
    application: helloshop-webservice
    deployment_group: helloshop-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true

